bin: improve aws-credentials-paste conditionals

diff --git a/home/.bin/aws-credentials-paste b/home/.bin/aws-credentials-paste
--- a/home/.bin/aws-credentials-paste
+++ b/home/.bin/aws-credentials-paste
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #=========================================================================================
 #
 #   DESCRIPTION: Retrieve AWS keys from clipboard and paste to your AWS credentials file
@@ -8,37 +8,42 @@
 
 AWS_ACCOUNTS=$HOME/.aws_accounts
 AWS_CREDENTIALS=$HOME/.aws/credentials
-TMPFILE=$(mktemp)
+
+[[ ! -x "$(command -v notify-send)" ]] && echo "Error: libnotify is not installed" >&2 && exit 1
+[[ ! -x "$(command -v xclip)" ]] && notify "Error: xclip is not installed" >&2 && exit 1
+
+tmpfile=$(mktemp)
 
 # redirect clipboard output to tmp file
-xclip -selection clipboard -o > $TMPFILE
+xclip -selection clipboard -o > $tmpfile
 
 # retrieve account number
-aws_number=$(egrep -o "[0-9]{12}" $TMPFILE)
+aws_number=$(egrep -o "[0-9]{12}" $tmpfile)
 
 # if there is no account number, exit
 if [[ -z $aws_number ]]; then
-   notify-send "AWS Credentials" "Paste failed"
-   exit 1
+    notify-send "AWS credentials" "Paste failed"
+    rm $tmpfile
+    exit 1
 fi
 
 # retrieve name by account number
 aws_name=$(grep $aws_number $AWS_ACCOUNTS | awk '{ print $2 }')
 
 # replace profile name
-sed -i "1s/.*/[$aws_name]/" $TMPFILE
+sed -i "1s/.*/[$aws_name]/" $tmpfile
 
 # if profile already exists, remove it
 sed -i "/$aws_name/,+4d" $AWS_CREDENTIALS
 
 # paste profile
 echo "" >> $AWS_CREDENTIALS
-cat $TMPFILE >> $AWS_CREDENTIALS
+cat $tmpfile >> $AWS_CREDENTIALS
 
 # nice formatting: add blank lines between profiles
 sed -i -e "/^$/d" -e "s/^\[.*\]\$/\n&/g" $AWS_CREDENTIALS
 sed -i '1d' $AWS_CREDENTIALS
 
-rm $TMPFILE
+rm $tmpfile
 
 notify-send "AWS credentials" "$aws_name pasted"
